# Generated by Django 2.2.1 on 2020-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pubIdentID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pub_ident_id',
            },
        ),
        migrations.CreateModel(
            name='pubKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('key_info', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'pub_keys',
            },
        ),
        migrations.CreateModel(
            name='pubLOLNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=150)),
                ('news_title', models.CharField(max_length=200)),
                ('news_title_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pub_lol_news',
            },
        ),
        migrations.CreateModel(
            name='pubLOLWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_name', models.CharField(max_length=50)),
                ('skin_url', models.CharField(max_length=500)),
                ('hero_name', models.CharField(max_length=10, null=True)),
                ('hero_id', models.IntegerField(null=True)),
                ('skin_short_url', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'pub_lol_wall',
            },
        ),
        migrations.CreateModel(
            name='pubWZNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=50)),
                ('news_title', models.CharField(max_length=200)),
                ('news_title_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pub_wz_news',
            },
        ),
        migrations.CreateModel(
            name='pubWZVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_name', models.CharField(max_length=100)),
                ('voice_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pub_wz_voice',
            },
        ),
        migrations.CreateModel(
            name='pubWZWall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_name', models.CharField(max_length=20)),
                ('skin_url', models.CharField(max_length=500)),
                ('hero_name', models.CharField(max_length=10, null=True)),
                ('hero_id', models.IntegerField(null=True)),
                ('skin_short_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pub_wz_wall',
            },
        ),
    ]
