# Generated by Django 2.2.1 on 2020-04-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto_reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubwzwall',
            name='mob_skin_short_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pubwzwall',
            name='mob_skin_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
