# Generated by Django 2.2.1 on 2020-03-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pubCardHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_id', models.CharField(max_length=20)),
                ('his_info', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'pub_card_text_history',
            },
        ),
        migrations.CreateModel(
            name='pubCardText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.IntegerField()),
                ('text_info', models.CharField(max_length=50, null=True)),
                ('text_story', models.CharField(max_length=500, null=True)),
                ('week', models.IntegerField(null=True)),
                ('holiday', models.CharField(max_length=50, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pub_card_text',
            },
        ),
        migrations.CreateModel(
            name='pubCardUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_puid', models.CharField(max_length=50, null=True)),
                ('wx_note', models.CharField(max_length=10, null=True)),
                ('wx_name', models.CharField(max_length=30, null=True)),
                ('qq', models.CharField(max_length=30, null=True)),
                ('state', models.BooleanField(default=False)),
                ('time_list', models.CharField(max_length=50, null=True)),
                ('time_num', models.IntegerField(null=True)),
                ('is_first', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_card_users',
            },
        ),
        migrations.CreateModel(
            name='pubEleGroupSn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField()),
                ('group_sn', models.CharField(max_length=100, null=True)),
                ('yet', models.IntegerField(default=0)),
                ('yet_max', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=200, null=True)),
                ('state', models.BooleanField(default=False)),
                ('from_name', models.CharField(max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('up_time', models.DateTimeField(auto_now=True, null=True)),
                ('retrys', models.IntegerField(null=True)),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pub_ele_group_sn',
            },
        ),
        migrations.CreateModel(
            name='pubEleHBRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=10, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('esource', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'pub_ele_hb_record',
            },
        ),
        migrations.CreateModel(
            name='pubEleID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('open_id', models.CharField(max_length=200)),
                ('sign', models.CharField(max_length=200)),
                ('sid', models.CharField(max_length=200)),
                ('mob_url', models.CharField(max_length=200, null=True)),
                ('qq', models.CharField(max_length=20, null=True)),
                ('qq_pwd', models.CharField(max_length=30, null=True)),
                ('is_five', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('is_cb', models.BooleanField(default=False)),
                ('id_info', models.CharField(max_length=50, null=True)),
                ('time_stamp', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'pub_ele_id',
            },
        ),
        migrations.CreateModel(
            name='pubEleSignInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_open_id', models.CharField(max_length=200)),
                ('sign_info', models.CharField(max_length=500)),
                ('sign_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_ele_sign_info',
            },
        ),
        migrations.CreateModel(
            name='pubEleSignUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_open_id', models.CharField(max_length=200, null=True)),
                ('wx_puid', models.CharField(max_length=50, null=True)),
                ('wx_note', models.CharField(max_length=20, null=True)),
                ('wx_name', models.CharField(max_length=30, null=True)),
                ('mobile', models.CharField(max_length=11, null=True)),
                ('sid', models.CharField(max_length=150, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('state', models.BooleanField(default=False)),
                ('is_bind', models.BooleanField(default=False)),
                ('is_sign', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_ele_sign_users',
            },
        ),
        migrations.CreateModel(
            name='pubEleSignVdtoken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_open_id', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=11)),
                ('vdtoken', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'pub_ele_sign_vdtoken',
            },
        ),
        migrations.CreateModel(
            name='pubEleTXUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_ele_tx_urls',
            },
        ),
        migrations.CreateModel(
            name='pubSMSList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=50)),
                ('mobile_url', models.CharField(max_length=500)),
                ('note', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_sms_list',
            },
        ),
        migrations.CreateModel(
            name='pubVarList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_name', models.CharField(max_length=20, unique=True)),
                ('var_info', models.CharField(max_length=2000)),
                ('note', models.CharField(max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_var_list',
            },
        ),
        migrations.CreateModel(
            name='pubVIPUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_puid', models.CharField(max_length=50)),
                ('wx_note', models.CharField(max_length=10)),
                ('wx_name', models.CharField(max_length=30)),
                ('num', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_vip_users',
            },
        ),
    ]
