# Generated by Django 2.2.1 on 2020-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pubEleSignCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_open_id', models.CharField(max_length=200)),
                ('sms_code', models.IntegerField()),
                ('is_send', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pub_ele_sign_hd_code',
            },
        ),
        migrations.AddField(
            model_name='pubcardusers',
            name='bind_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pubcardusers',
            name='wx_open_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pubelesignusers',
            name='bind_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pubelesignusers',
            name='qq',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
