# Generated by Django 2.2.3 on 2020-12-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=255)),
                ('ori_url', models.TextField()),
                ('period', models.DateTimeField()),
            ],
            options={
                'db_table': 'pub_short_url',
            },
        ),
    ]
